import chalk from 'chalk';

export const postinstallCommand = async (): Promise<void> => {
  console.log('');
  console.log(chalk.cyan('════════════════════════════════════════'));
  console.log(chalk.cyan('   MoiCle installed!'));
  console.log(chalk.cyan('════════════════════════════════════════'));
  console.log('');
  console.log('Run the following command to set up:');
  console.log('');
  console.log(chalk.green('  moicle install'));
  console.log('');
  console.log('Or with options:');
  console.log(chalk.gray('  moicle install --global   # Install to ~/.claude/'));
  console.log(chalk.gray('  moicle install --project  # Install to ./.claude/'));
  console.log(chalk.gray('  moicle install --all      # Install to both'));
  console.log(chalk.gray('  moicle install --target codex --global       # Codex skills → ~/.codex/'));
  console.log(chalk.gray('  moicle install --target antigravity --global # Antigravity skills → ~/.gemini/'));
  console.log(chalk.gray('  moicle install --target cursor               # Cursor rules → ~/.cursor/'));
  console.log(chalk.gray('  moicle install --target windsurf             # Windsurf rules'));
  console.log('');
  console.log('Other commands:');
  console.log(chalk.gray('  moicle list       # List installed items'));
  console.log(chalk.gray('  moicle status     # Show enabled/disabled status'));
  console.log(chalk.gray('  moicle enable     # Enable items'));
  console.log(chalk.gray('  moicle disable    # Disable items'));
  console.log(chalk.gray('  moicle upgrade    # Upgrade to latest version'));
  console.log(chalk.gray('  moicle uninstall  # Remove installations'));
  console.log('');
};
